### ISSUE TITLE
it doesn't work?

### ISSUE THREAD

**Issue by Freizeitalkoholiker** [Matze5593/Modbus_Siemens_PAC2200-Home-Assistat#1]
Hi. 
I am a newbie and have exactly one PAC2200 and Home Assistant. It does not work for me, what else do I need to consider?

![PAC2200 HA](https://github.com/Matze5593/Modbus_Siemens_PAC2200-Home-Assistat/assets/145748447/d0d6c73d-1973-4210-9aed-bf668a1f8a01)

**Comment by Matze5593** [comment]
Do you have the correct IP address, port and slave id?

**Comment by Freizeitalkoholiker** [comment]
Good question... 
IP: Yes
Slave: how do I find out? I only have the PAC2200.
How can I check the communication? Is there a tool for this?

I use one 7KM2200-2EA40-1JA1 - only Modbus TCP with MID

**Comment by Freizeitalkoholiker** [comment]
I've found the mistake. Silly me, I actually entered the wrong IP address: 192.168.010.058
The correct IP is: 192.168.10.58

I apologize and THANK YOU!
